# Generated by Django 4.1.5 on 2023-01-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applience",
            fields=[
                (
                    "applience",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id оборудования",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        max_length=30,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("плохое", "плохое"),
                            ("Удовлетворительное", "удовлетворительное"),
                            ("хорошее", "хорошее"),
                        ],
                        max_length=30,
                    ),
                ),
                ("coast", models.FloatField(blank=True, null=True)),
                ("manafacture", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "данные о продукции",
                "verbose_name_plural": "продукция",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "client",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id клиента"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="фамилия"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        max_length=12, verbose_name="контактная информация"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "данные о клиентах",
                "verbose_name_plural": "клиента",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id клуба"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        max_length=30,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                ("cost", models.CharField(max_length=30, verbose_name="адрес")),
                ("amount", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "данные о продукции",
                "verbose_name_plural": "продукция",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "provider",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id провайдера"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="имя"),
                ),
                (
                    "contact",
                    models.CharField(
                        max_length=12, verbose_name="контактная информация"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "данные о поставщиках",
                "verbose_name_plural": "поставщика",
            },
        ),
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "resouces",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id ресурса"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        max_length=30,
                        unique=True,
                        verbose_name="название ресурса",
                    ),
                ),
                ("cost_per_tonna", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "данные о ресурсах",
                "verbose_name_plural": "ресурс",
            },
        ),
        migrations.CreateModel(
            name="ContrAgent",
            fields=[
                (
                    "contrAgent",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id контрагента"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="имя"),
                ),
                ("remainder", models.FloatField(blank=True, default=0.0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.client",
                        verbose_name="поставщик",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.provider",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "данные о контрагентах",
                "verbose_name_plural": "контрагента",
            },
        ),
    ]
