# Generated by Django 4.1.5 on 2023-01-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applience",
            options={
                "verbose_name": "данные о оборудовании",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "verbose_name": "данные о клиентах",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "verbose_name": "данные о поставщиках",
                "verbose_name_plural": "поставщики",
            },
        ),
        migrations.AlterModelOptions(
            name="resources",
            options={
                "verbose_name": "данные о ресурсах",
                "verbose_name_plural": "ресурсы",
            },
        ),
    ]
