# Generated by Django 4.1.5 on 2023-01-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_applience_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contragent",
            options={
                "verbose_name": "данные о контрагентах",
                "verbose_name_plural": "контрагенты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="aplience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.applience",
                verbose_name="оборудование",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.resources",
                verbose_name="используемые ресурсы",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="Product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.product",
                verbose_name="продукт",
            ),
        ),
    ]
