# Generated by Django 4.1.5 on 2023-01-10 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_alter_contragent_options_product_aplience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applience",
            name="coast",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="затрата в час",
            ),
        ),
        migrations.AlterField(
            model_name="applience",
            name="manafacture",
            field=models.CharField(max_length=30, verbose_name="производитель"),
        ),
        migrations.AlterField(
            model_name="contragent",
            name="remainder",
            field=models.FloatField(
                blank=True,
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="остатоки",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="кол-во",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="цена",
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="cost_per_tonna",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="стоимость за тонну",
            ),
        ),
    ]
